
SET FOREIGN_KEY_CHECKS = 0;
/* 
Create table */
CREATE TABLE IF NOT EXISTS EMPLOYEE
(Fname varchar(15) NOT NULL,
Minit CHAR,
Lname VARCHAR(15) NOT NULL,
Ssn CHAR(9) NOT NULL,
Bdate	DATE,
Address VARCHAR(30),
Sex CHAR,
Salary DECIMAL(10,2),
Super_ssn CHAR(9),
Dno INT NOT NULL,
PRIMARY KEY (Ssn),
FOREIGN KEY(Super_ssn) REFERENCES EMPLOYEE(Ssn),
FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber));


CREATE TABLE IF NOT EXISTS DEPARTMENT
(Dname VARCHAR(15) NOT NULL,
Dnumber INT NOT NULL,
Mgr_ssn CHAR(9) NOT NULL,
Mgr_start_date DATE,
PRIMARY KEY (Dnumber),
UNIQUE(Dname),
FOREIGN KEY(Mgr_ssn) REFERENCES EMPLOYEE(Ssn));


SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE IF NOT EXISTS DEPT_LOCATIONS
(Dnumber INT NOT NULL,
Dlocation Varchar(15) NOT NULL,
PRIMARY KEY (Dnumber,Dlocation),
FOREIGN KEY(Dnumber) REFERENCES DEPARTMENT(Dnumber));



CREATE TABLE IF NOT EXISTS PROJECT
(Pname VARCHAR(15) NOT NULL,
Pnumber INT NOT NULL,
Plocation VARCHAR(15) NOT NULL,
Dnum INT NOT NULL,
PRIMARY KEY (Pnumber),
UNIQUE(Pname),
FOREIGN KEY(Dnum) REFERENCES DEPARTMENT(Dnumber));




CREATE TABLE IF NOT EXISTS WORKS_ON
(Essn Char(9) NOT NULL,
Pno INT NOT NULL,
Hours Decimal(3,1) NOT NULL,
Primary KEY (Essn,Pno),
FOREIGN KEY(Essn) REFERENCES EMPLOYEE(SSn),
FOREIGN KEY(Pno) REFERENCES PROJECT(Pnumber)
);



CREATE TABLE IF NOT EXISTS DEPENDENT
(Essn Char(9) NOT NULL,
Dependent_name VARCHAR(15) NOT NULL,
Sex CHAR,
Bdate DATE,
Relationship VARCHAR(8),
Primary KEY (Essn,Dependent_name),
FOREIGN KEY(Essn) REFERENCES EMPLOYEE(SSn));


SET FOREIGN_KEY_CHECKS = 1;